### PR TITLE
WIP: Updates for general election

### PR DESCRIPTION
**Pull request by carlmjohnson**

### CODE REVIEW

**Comment by carlmjohnson** [comment]
Still working on it! I'm waiting for kalani to finish updating the Google Sheet and then I need to figure out how to display the candidates who won't be in the general. Maybe a big banner saying PRIMARY LOSER or something.

**Comment by carlmjohnson** [comment]
I think that would be good from a navigation POV, but then the old URLs would become 404s. Maybe if we had some redirects or something.

**Comment by carlmjohnson** [comment]
screen shot 2018-08-24 at 11 07 53 am
screen shot 2018-08-24 at 11 07 04 am

**Comment by carolinp** [comment]
yeah, i think if we archive and redirect it, that will be a lot less confusing for the user experience

**Comment by carlmjohnson** [comment]
I moved the primary only people into content/primary and added redirects from the old pages. Seems good. Just waiting on some more changes from Kalani and then this should be ready to merge.

**Comment by carlmjohnson** [comment]
@carolinp can you take one last glance, and then I'll merge?

**Pull request merged**
